name: genefam-dist
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9
  - c-compiler
  - pip
  - setuptools>=77
  - wheel
  - numpy>=1.23
  - dendropy>=4.6
  - pytest
  - foldmason
  - pip:
      - -e .
